export const ONBOARDING = 'Onboarding'
export const LOGIN = 'Login'
export const FORGOT_PASSWORD = 'ForgotPassword'
export const CREATE_ACCOUNT = 'CreateAccount'
export const CREATE_ACCOUNT_SUCCESS = 'CreateAccountSuccess'